### ISSUE TITLE
[Bug] Client crashing

### ISSUE THREAD

**Issue by Sentakuu** [Lyzev/Schizoid#77]
### Describe the bug

when ever i open schizoid fabric 1.20.6 im using it just crashes and like i get the fabric logs app or how its called and i get this: 
Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod schizoid
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:514)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:149)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:512)
	... 3 more

### Steps to reproduce

```bash
just launch mc 1.20.6 fabric latest version idk how to fix it :(
```

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lyzev** [comment]
seems like you are using the shadow jar, which should not be used

**Comment by Lyzev** [comment]
Now that it works for you, I will close this issue
